### ISSUE TITLE
Improve error messege on missing id.txt

### ISSUE THREAD

**Issue by jmdha** [jamadaha/chess_bot#18]

**Comment by henrikac** [comment]
Unless you are trying to not use any 3rd party stuff, maybe use [dotenv](https://www.npmjs.com/package/dotenv) instead?

**Comment by jmdha** [comment]
> Unless you are trying to not use any 3rd party stuff, maybe use [dotenv](https://www.npmjs.com/package/dotenv) instead?

Didn't know that was a thing, seems like a way better method of doing it.
Thanks!
